services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - .:/app:cached
    working_dir: /app
    environment:
      RACK_ENV: ${RACK_ENV}
      DISCORD_API_TOKEN: ${DISCORD_API_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      REDIS_URL: ${REDIS_URL}
      TZ: ${TZ}
      # POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      - redis
    networks:
      - botnetwork
    entrypoint: |
      bundle exec rackup --host 0.0.0.0 -p 4567
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - botnetwork

networks:
  botnetwork:
